---
- name: Download AWS SSM
  ansible.builtin.get_url:
    url: "{{ awscli_ssm_url }}"
    dest: "{{ awscli_download_path }}"
    checksum: "{{ awscli_ssm_checksum }}"
    mode: 'u=rw,go=r'
  register: downloaded_file
  become: true

- name: Install AWS SSM (RHEL)
  ansible.builtin.yum:
    name: "{{ downloaded_file.dest }}"
    state: present
    disable_gpg_check: true
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install AWS SSM (Debian)
  ansible.builtin.apt:
    deb: "{{ downloaded_file.dest }}"
    state: present
  when: ansible_os_family == 'Debian'
  become: true
